### PR TITLE
upgrade to MinVer 1.0.0-rc.1

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by adamralph** [comment]
It looks like the build is failing for an unrelated reason.

**Comment by cameronfletcher** [comment]
Yeah. I'm taking a look.

**Comment by adamralph** [comment]
Could it be the same problem as in https://github.com/LykkeCorp/apollo/pull/111 ?

**Comment by cameronfletcher** [comment]
There was an odd issue relating to (I can only imagine) that `All` package and an Entity Framework downgrade - or some nonsense like that. Entity Framework FTW?
Anyway, a rebase should not fail for that reason.

**Comment by adamralph** [comment]
Not sure I understand any of that. 😉

**Comment by adamralph** [comment]
Rebased, and switched from beta 4 to RC 1.

**Pull request merged**
